// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuny3GaI2ZITZJrTFIlqdpp_cS_cade_M',
    appId: '1:1048884445244:web:c3b129e37d7eee163e0339',
    messagingSenderId: '1048884445244',
    projectId: 'chattapp-b2b64',
    authDomain: 'chattapp-b2b64.firebaseapp.com',
    storageBucket: 'chattapp-b2b64.appspot.com',
    measurementId: 'G-7MPK6W2CVJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJVo4kx4gP1CTEl5ggP9K_hUX2JKI8zRk',
    appId: '1:1048884445244:android:28307f1110a9bb043e0339',
    messagingSenderId: '1048884445244',
    projectId: 'chattapp-b2b64',
    storageBucket: 'chattapp-b2b64.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrekr2_yDppaQFu4GMpYQxN8vpPJUjOD8',
    appId: '1:1048884445244:ios:76b04b71e27fc8b03e0339',
    messagingSenderId: '1048884445244',
    projectId: 'chattapp-b2b64',
    storageBucket: 'chattapp-b2b64.appspot.com',
    iosClientId: '1048884445244-thn2md5mll5vmobhd2bc0nc1d1me9gh3.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrekr2_yDppaQFu4GMpYQxN8vpPJUjOD8',
    appId: '1:1048884445244:ios:76b04b71e27fc8b03e0339',
    messagingSenderId: '1048884445244',
    projectId: 'chattapp-b2b64',
    storageBucket: 'chattapp-b2b64.appspot.com',
    iosClientId: '1048884445244-thn2md5mll5vmobhd2bc0nc1d1me9gh3.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopapp',
  );
}
